force-app/main/default/objects/Score__c/Score__c.object-meta.xml
<CustomObject>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Score__c/fields/CreatedByGuestUser__c.field-meta.xml
<CustomField>
    <fullName>CreatedByGuestUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created By Guest User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Player_Name__c.field-meta.xml
<CustomField>
    <fullName>Player_Name__c</fullName>
    <label>Player Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Score__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SnakeGameController.cls
public with sharing class SnakeGameController {
    @AuraEnabled(cacheable=true)
    public static List<Score__c> getTopTenScoreList(){
        return [SELECT Id, Score__c, Player_Name__c, CreatedDate
                FROM Score__c
                WHERE CreatedByGuestUser__c = true
                AND Score__c > 0
                WITH SECURITY_ENFORCED
                ORDER BY Score__c DESC                
                LIMIT 10];
    }
}